// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClassWestWindsystem.Entity;

public partial class Territory
{
    [Key,DatabaseGenerated(DatabaseGeneratedOption.None)]
    [StringLength(20,ErrorMessage ="Territory ID is limited to 20 characters", MinimumLength = 8)]
    public string TerritoryID { get; set; }

    [Required(ErrorMessage ="Territory Description is required field")]
    [StringLength(50,ErrorMessage ="Territory Description is limited to 50 Characters")]
    public string TerritoryDescription { get; set; }

    public int RegionID { get; set; }

    [ForeignKey("RegionID")]
    [InverseProperty("Territories")]
    public virtual Region Region { get; set; }

    [ForeignKey("TerritoryID")]
    [InverseProperty("Territories")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}